#!/bin/sh

echo "🚑️ Running pre-commit checks..."

echo ""
echo "🩺️ Running type check..."
if ! pnpm type-check; then
  echo "🐛 Type check failed. Aborting commit."
  exit 1
fi
echo "✅ Type check passed."
echo ""

echo ""
echo "🚨 Running lint..."
if ! pnpm lint --max-warnings=0; then
  echo "🐛 Lint failed. Aborting commit."
  exit 1
fi
echo "✅ Lint passed."
echo ""

echo ""
echo "🔍 Running format..."
pnpm format:silent
echo "✅ Format passed."
echo ""

echo ""
echo "🚑️ Pre-commit checks passed. Committing..."
exit 0